# Generated by Django 2.1.7 on 2019-03-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_encountersform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EncountersForm',
            new_name='Encounter',
        ),
    ]
