# Generated by Django 2.1.7 on 2019-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190312_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='admit_date',
            new_name='admit_date_time',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='discharge_date',
            new_name='discharge_date_time',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='encounter_age_criteria',
            new_name='encounter_date_criteria',
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_date',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='length_of_stay',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
