# Generated by Django 2.1.7 on 2019-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190312_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='length_of_stay',
            field=models.BooleanField(),
        ),
    ]
