# Generated by Django 2.1.7 on 2019-03-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190312_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intended_used',
            field=models.CharField(choices=[('Grant Proposal', 'Grant Proposal'), ('Poster', 'Poster'), ('Manuscript', 'Manuscript'), ('Presentation', 'Presentation'), ('Other ', 'Other ')], default='Identified Dataset', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='irb_approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='recruitment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='research_topic',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
